### ISSUE TITLE
Libraries requirement

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/ckeditor_codemirror#1]
Ckeditor_codemirror requires the Libraries API module, but that's been deprecated in Backdrop. This is from the Libraries API module page in Backdrop:

If you're a module maintainer and currently depend on Libraries API, please replace Libraries API-specific functions with their Backdrop core equivalents:

hook_libraries_info() -> [hook_library_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_library_info/1) hook_libraries_info_alter() -> [hook_library_info_alter()](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_library_info_alter/1) libraries_load() -> [backdrop_add_library()](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_library/1) libraries_info() -> [backdrop_get_library()](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_get_library/1) Note that this isn't simply a matter of renaming the functions. You will need to rewrite some of your code. Check the API documentation for more information.

**Comment by laryn** [comment]
@pgrayove-mcpl I've made some modifications to convert from the Libraries module to internal Backdrop equivalents. I'll submit as a PR shortly.

Some notes: 

- I've bundled the latest version of the library directly in the module, as is typical in Backdrop. If this library has new releases (especially security releases), you will have to download the new version and replace the contents of `/library/codemirror` with the new version, then test functionality again and make a new release if all is well.
- Right now I've got this set up to automatically enable Codemirror on all CKEditor-enabled text areas. This could be modified in the future to add a configuration setting in the CKEditor settings admin page, but I haven't spent time on that now.
- I haven't done any work on tests or drush integration (and I'm not sure how important they are since we're bundling the library directly).
- I also haven't done anything with the `ckeditor_codemirror_wysiwyg` submodule that is bundled here and I'd probably suggest it can be removed since I don't think `wysiwyg` is ported and `ckeditor` is included in core.
